//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4952.
// 
#pragma warning disable 1591

namespace SprintWseLibrary.com.sprint.WholesaleUsageInquiryService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
  


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "WholesaleUsageInquiryBinding", Namespace = "http://integration.sprint.com/eai/services/WholesaleUsageInquiry/v1/WholesaleUsag" +
        "eInquiry.wsdl")]
    public partial class WholesaleUsageInquiryService : Microsoft.Web.Services3.WebServicesClientProtocol
    {

        private WsMessageHeaderType wsMessageHeaderField;

        private System.Threading.SendOrPostCallback QuerySubscriptionUsageOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public WholesaleUsageInquiryService()
        {
            this.Url = global::SprintWseLibrary.Properties.Settings.Default.PingTestClient_com_sprint_WholesaleUsageInquiryService_WholesaleUsageInquiryService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public WsMessageHeaderType wsMessageHeader
        {
            get
            {
                return this.wsMessageHeaderField;
            }
            set
            {
                this.wsMessageHeaderField = value;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event QuerySubscriptionUsageCompletedEventHandler QuerySubscriptionUsageCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("wsMessageHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("querySubscriptionUsage", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("querySubscriptionUsageResponse", Namespace = "http://integration.sprint.com/interfaces/WholesaleUsageInquiry/v1/UsageInquiryEnv" +
            "elope.xsd")]
        public QuerySubscriptionUsageReply QuerySubscriptionUsage([System.Xml.Serialization.XmlElementAttribute("querySubscriptionUsage", Namespace = "http://integration.sprint.com/interfaces/WholesaleUsageInquiry/v1/UsageInquiryEnv" +
            "elope.xsd")] QuerySubscriptionUsageRequest querySubscriptionUsage1)
        {
            object[] results = this.Invoke("QuerySubscriptionUsage", new object[] {
                        querySubscriptionUsage1});
            return ((QuerySubscriptionUsageReply)(results[0]));
        }

        /// <remarks/>
        public void QuerySubscriptionUsageAsync(QuerySubscriptionUsageRequest querySubscriptionUsage1)
        {
            this.QuerySubscriptionUsageAsync(querySubscriptionUsage1, null);
        }

        /// <remarks/>
        public void QuerySubscriptionUsageAsync(QuerySubscriptionUsageRequest querySubscriptionUsage1, object userState)
        {
            if ((this.QuerySubscriptionUsageOperationCompleted == null))
            {
                this.QuerySubscriptionUsageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuerySubscriptionUsageOperationCompleted);
            }
            this.InvokeAsync("QuerySubscriptionUsage", new object[] {
                        querySubscriptionUsage1}, this.QuerySubscriptionUsageOperationCompleted, userState);
        }

        private void OnQuerySubscriptionUsageOperationCompleted(object arg)
        {
            if ((this.QuerySubscriptionUsageCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuerySubscriptionUsageCompleted(this, new QuerySubscriptionUsageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    [System.Xml.Serialization.XmlRootAttribute("wsMessageHeader", Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2", IsNullable = false)]
    public partial class WsMessageHeaderType : System.Web.Services.Protocols.SoapHeader
    {

        private TrackingMessageHeaderType trackingMessageHeaderField;

        private SecurityMessageHeaderType securityMessageHeaderField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public TrackingMessageHeaderType trackingMessageHeader
        {
            get
            {
                return this.trackingMessageHeaderField;
            }
            set
            {
                this.trackingMessageHeaderField = value;
            }
        }

        /// <remarks/>
        public SecurityMessageHeaderType securityMessageHeader
        {
            get
            {
                return this.securityMessageHeaderField;
            }
            set
            {
                this.securityMessageHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    public partial class TrackingMessageHeaderType
    {

        private string applicationIdField;

        private string applicationUserIdField;

        private string consumerIdField;

        private string messageIdField;

        private string conversationIdField;

        private string timeToLiveField;

        private long replyCompletionCodeField;

        private bool replyCompletionCodeFieldSpecified;

        private System.DateTime messageDateTimeStampField;

        /// <remarks/>
        public string applicationId
        {
            get
            {
                return this.applicationIdField;
            }
            set
            {
                this.applicationIdField = value;
            }
        }

        /// <remarks/>
        public string applicationUserId
        {
            get
            {
                return this.applicationUserIdField;
            }
            set
            {
                this.applicationUserIdField = value;
            }
        }

        /// <remarks/>
        public string consumerId
        {
            get
            {
                return this.consumerIdField;
            }
            set
            {
                this.consumerIdField = value;
            }
        }

        /// <remarks/>
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        public string conversationId
        {
            get
            {
                return this.conversationIdField;
            }
            set
            {
                this.conversationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string timeToLive
        {
            get
            {
                return this.timeToLiveField;
            }
            set
            {
                this.timeToLiveField = value;
            }
        }

        /// <remarks/>
        public long replyCompletionCode
        {
            get
            {
                return this.replyCompletionCodeField;
            }
            set
            {
                this.replyCompletionCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool replyCompletionCodeSpecified
        {
            get
            {
                return this.replyCompletionCodeFieldSpecified;
            }
            set
            {
                this.replyCompletionCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime messageDateTimeStamp
        {
            get
            {
                return this.messageDateTimeStampField;
            }
            set
            {
                this.messageDateTimeStampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleUsageInquiry/v1/UsageInquiryEnv" +
        "elope.xsd")]
    public partial class CallDetailRecord
    {

        private decimal airtimeMinutesField;

        private bool airtimeMinutesFieldSpecified;

        private string activityUnitField;

        private string contentPartnerNameField;

        private bool boboIndicatorField;

        private bool boboIndicatorFieldSpecified;

        private System.DateTime callDateField;

        private bool callDateFieldSpecified;

        private System.DateTime callTimeField;

        private bool callTimeFieldSpecified;

        private string callingNumberField;

        private string calledDestinationField;

        private string calledNumberField;

        private string homeCallField;

        private string naiField;

        private string rpdrServiceCodeField;

        private string sidField;

        private string usageQuantityField;

        private string usageSourceIndField;

        private string contentTypeNameField;

        private string contentDetailedDescriptionField;

        /// <remarks/>
        public decimal airtimeMinutes
        {
            get
            {
                return this.airtimeMinutesField;
            }
            set
            {
                this.airtimeMinutesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool airtimeMinutesSpecified
        {
            get
            {
                return this.airtimeMinutesFieldSpecified;
            }
            set
            {
                this.airtimeMinutesFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string activityUnit
        {
            get
            {
                return this.activityUnitField;
            }
            set
            {
                this.activityUnitField = value;
            }
        }

        /// <remarks/>
        public string contentPartnerName
        {
            get
            {
                return this.contentPartnerNameField;
            }
            set
            {
                this.contentPartnerNameField = value;
            }
        }

        /// <remarks/>
        public bool boboIndicator
        {
            get
            {
                return this.boboIndicatorField;
            }
            set
            {
                this.boboIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool boboIndicatorSpecified
        {
            get
            {
                return this.boboIndicatorFieldSpecified;
            }
            set
            {
                this.boboIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime callDate
        {
            get
            {
                return this.callDateField;
            }
            set
            {
                this.callDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callDateSpecified
        {
            get
            {
                return this.callDateFieldSpecified;
            }
            set
            {
                this.callDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime callTime
        {
            get
            {
                return this.callTimeField;
            }
            set
            {
                this.callTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool callTimeSpecified
        {
            get
            {
                return this.callTimeFieldSpecified;
            }
            set
            {
                this.callTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string callingNumber
        {
            get
            {
                return this.callingNumberField;
            }
            set
            {
                this.callingNumberField = value;
            }
        }

        /// <remarks/>
        public string calledDestination
        {
            get
            {
                return this.calledDestinationField;
            }
            set
            {
                this.calledDestinationField = value;
            }
        }

        /// <remarks/>
        public string calledNumber
        {
            get
            {
                return this.calledNumberField;
            }
            set
            {
                this.calledNumberField = value;
            }
        }

        /// <remarks/>
        public string homeCall
        {
            get
            {
                return this.homeCallField;
            }
            set
            {
                this.homeCallField = value;
            }
        }

        /// <remarks/>
        public string nai
        {
            get
            {
                return this.naiField;
            }
            set
            {
                this.naiField = value;
            }
        }

        /// <remarks/>
        public string rpdrServiceCode
        {
            get
            {
                return this.rpdrServiceCodeField;
            }
            set
            {
                this.rpdrServiceCodeField = value;
            }
        }

        /// <remarks/>
        public string sid
        {
            get
            {
                return this.sidField;
            }
            set
            {
                this.sidField = value;
            }
        }

        /// <remarks/>
        public string usageQuantity
        {
            get
            {
                return this.usageQuantityField;
            }
            set
            {
                this.usageQuantityField = value;
            }
        }

        /// <remarks/>
        public string usageSourceInd
        {
            get
            {
                return this.usageSourceIndField;
            }
            set
            {
                this.usageSourceIndField = value;
            }
        }

        /// <remarks/>
        public string contentTypeName
        {
            get
            {
                return this.contentTypeNameField;
            }
            set
            {
                this.contentTypeNameField = value;
            }
        }

        /// <remarks/>
        public string contentDetailedDescription
        {
            get
            {
                return this.contentDetailedDescriptionField;
            }
            set
            {
                this.contentDetailedDescriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleUsageInquiry/v1/UsageInquiryEnv" +
        "elope.xsd")]
    public partial class QuerySubscriptionUsageReply
    {

        private string mdnField;

        private System.DateTime fromDateField;

        private bool fromDateFieldSpecified;

        private System.DateTime toDateField;

        private bool toDateFieldSpecified;

        private UsageTypeCode usageTypeField;

        private bool usageTypeFieldSpecified;

        private decimal totalCallsField;

        private bool totalCallsFieldSpecified;

        private decimal totalAirtimeUsageField;

        private bool totalAirtimeUsageFieldSpecified;

        private bool areMoreCallDetailsField;

        private bool areMoreCallDetailsFieldSpecified;

        private CallDetailRecord[] callDetailListField;

        /// <remarks/>
        public string mdn
        {
            get
            {
                return this.mdnField;
            }
            set
            {
                this.mdnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime fromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromDateSpecified
        {
            get
            {
                return this.fromDateFieldSpecified;
            }
            set
            {
                this.fromDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime toDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toDateSpecified
        {
            get
            {
                return this.toDateFieldSpecified;
            }
            set
            {
                this.toDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public UsageTypeCode usageType
        {
            get
            {
                return this.usageTypeField;
            }
            set
            {
                this.usageTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usageTypeSpecified
        {
            get
            {
                return this.usageTypeFieldSpecified;
            }
            set
            {
                this.usageTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal totalCalls
        {
            get
            {
                return this.totalCallsField;
            }
            set
            {
                this.totalCallsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalCallsSpecified
        {
            get
            {
                return this.totalCallsFieldSpecified;
            }
            set
            {
                this.totalCallsFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal totalAirtimeUsage
        {
            get
            {
                return this.totalAirtimeUsageField;
            }
            set
            {
                this.totalAirtimeUsageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalAirtimeUsageSpecified
        {
            get
            {
                return this.totalAirtimeUsageFieldSpecified;
            }
            set
            {
                this.totalAirtimeUsageFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool areMoreCallDetails
        {
            get
            {
                return this.areMoreCallDetailsField;
            }
            set
            {
                this.areMoreCallDetailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool areMoreCallDetailsSpecified
        {
            get
            {
                return this.areMoreCallDetailsFieldSpecified;
            }
            set
            {
                this.areMoreCallDetailsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("callDetailRecord", IsNullable = false)]
        public CallDetailRecord[] callDetailList
        {
            get
            {
                return this.callDetailListField;
            }
            set
            {
                this.callDetailListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleUsageInquiry/v1/UsageInquiryEnv" +
        "elope.xsd")]
    public enum UsageTypeCode
    {

        /// <remarks/>
        B,

        /// <remarks/>
        U,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleUsageInquiry/v1/UsageInquiryEnv" +
        "elope.xsd")]
    public partial class UsageCategory
    {

        private bool allField;

        private bool allFieldSpecified;

        private bool circuitSwitchDataField;

        private bool circuitSwitchDataFieldSpecified;

        private bool ipDataField;

        private bool ipDataFieldSpecified;

        private bool smsDataField;

        private bool smsDataFieldSpecified;

        private bool voiceDataField;

        private bool voiceDataFieldSpecified;

        /// <remarks/>
        public bool all
        {
            get
            {
                return this.allField;
            }
            set
            {
                this.allField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool allSpecified
        {
            get
            {
                return this.allFieldSpecified;
            }
            set
            {
                this.allFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool circuitSwitchData
        {
            get
            {
                return this.circuitSwitchDataField;
            }
            set
            {
                this.circuitSwitchDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool circuitSwitchDataSpecified
        {
            get
            {
                return this.circuitSwitchDataFieldSpecified;
            }
            set
            {
                this.circuitSwitchDataFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool ipData
        {
            get
            {
                return this.ipDataField;
            }
            set
            {
                this.ipDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ipDataSpecified
        {
            get
            {
                return this.ipDataFieldSpecified;
            }
            set
            {
                this.ipDataFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool smsData
        {
            get
            {
                return this.smsDataField;
            }
            set
            {
                this.smsDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool smsDataSpecified
        {
            get
            {
                return this.smsDataFieldSpecified;
            }
            set
            {
                this.smsDataFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool voiceData
        {
            get
            {
                return this.voiceDataField;
            }
            set
            {
                this.voiceDataField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool voiceDataSpecified
        {
            get
            {
                return this.voiceDataFieldSpecified;
            }
            set
            {
                this.voiceDataFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleUsageInquiry/v1/UsageInquiryEnv" +
        "elope.xsd")]
    public partial class MobileEquipmentIdentifier
    {

        private string itemField;

        private ItemChoiceType1 itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mobileEquipmentIdentifierDec", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("mobileEquipmentIdentifierHex", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleUsageInquiry/v1/UsageInquiryEnv" +
        "elope.xsd", IncludeInSchema = false)]
    public enum ItemChoiceType1
    {

        /// <remarks/>
        mobileEquipmentIdentifierDec,

        /// <remarks/>
        mobileEquipmentIdentifierHex,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleUsageInquiry/v1/UsageInquiryEnv" +
        "elope.xsd")]
    public partial class ElectronicSerialNumber
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("electronicSerialNumberDec", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("electronicSerialNumberHex", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleUsageInquiry/v1/UsageInquiryEnv" +
        "elope.xsd", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        electronicSerialNumberDec,

        /// <remarks/>
        electronicSerialNumberHex,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleUsageInquiry/v1/UsageInquiryEnv" +
        "elope.xsd")]
    public partial class SerialNumber
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("electronicSerialNumber", typeof(ElectronicSerialNumber))]
        [System.Xml.Serialization.XmlElementAttribute("mobileEquipmentIdentifier", typeof(MobileEquipmentIdentifier))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleUsageInquiry/v1/UsageInquiryEnv" +
        "elope.xsd")]
    public partial class QuerySubscriptionUsageRequest
    {

        private SerialNumber esnField;

        private System.DateTime prevEndingCallDateField;

        private bool prevEndingCallDateFieldSpecified;

        private System.DateTime prevEndingCallTimeField;

        private bool prevEndingCallTimeFieldSpecified;

        private UsageCategory usageCategoryField;

        private string mdnField;

        private System.DateTime fromDateField;

        private bool fromDateFieldSpecified;

        private System.DateTime toDateField;

        private bool toDateFieldSpecified;

        private UsageTypeCode usageTypeField;

        private bool usageTypeFieldSpecified;

        /// <remarks/>
        public SerialNumber esn
        {
            get
            {
                return this.esnField;
            }
            set
            {
                this.esnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime prevEndingCallDate
        {
            get
            {
                return this.prevEndingCallDateField;
            }
            set
            {
                this.prevEndingCallDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prevEndingCallDateSpecified
        {
            get
            {
                return this.prevEndingCallDateFieldSpecified;
            }
            set
            {
                this.prevEndingCallDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "time")]
        public System.DateTime prevEndingCallTime
        {
            get
            {
                return this.prevEndingCallTimeField;
            }
            set
            {
                this.prevEndingCallTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prevEndingCallTimeSpecified
        {
            get
            {
                return this.prevEndingCallTimeFieldSpecified;
            }
            set
            {
                this.prevEndingCallTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public UsageCategory usageCategory
        {
            get
            {
                return this.usageCategoryField;
            }
            set
            {
                this.usageCategoryField = value;
            }
        }

        /// <remarks/>
        public string mdn
        {
            get
            {
                return this.mdnField;
            }
            set
            {
                this.mdnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime fromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fromDateSpecified
        {
            get
            {
                return this.fromDateFieldSpecified;
            }
            set
            {
                this.fromDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime toDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool toDateSpecified
        {
            get
            {
                return this.toDateFieldSpecified;
            }
            set
            {
                this.toDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public UsageTypeCode usageType
        {
            get
            {
                return this.usageTypeField;
            }
            set
            {
                this.usageTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usageTypeSpecified
        {
            get
            {
                return this.usageTypeFieldSpecified;
            }
            set
            {
                this.usageTypeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    public partial class BasicCredentialInfoType
    {

        private string idField;

        private string passwordField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    public partial class SdcLoginCredentialsType
    {

        private string userIdField;

        private string passwordField;

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    public partial class SecurityMessageHeaderType
    {

        private object itemField;

        private string corpIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("basicCredentialInfo", typeof(BasicCredentialInfoType))]
        [System.Xml.Serialization.XmlElementAttribute("pin", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("sdcLoginCredentials", typeof(SdcLoginCredentialsType))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public string corpId
        {
            get
            {
                return this.corpIdField;
            }
            set
            {
                this.corpIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void QuerySubscriptionUsageCompletedEventHandler(object sender, QuerySubscriptionUsageCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuerySubscriptionUsageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal QuerySubscriptionUsageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public QuerySubscriptionUsageReply Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((QuerySubscriptionUsageReply)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591