//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4952.
// 
#pragma warning disable 1591

namespace SprintWseLibrary.com.sprint.WholesalePortMessageService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    using WholesaleQueryCsaService;



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "WholesalePortMessageServiceBinding", Namespace = "http://integration.sprint.com/eai/services/WholesalePortMessageService/v1/Wholesa" +
        "lePortMessageService.wsdl")]
    public partial class WholesalePortMessageService : Microsoft.Web.Services3.WebServicesClientProtocol
    {

        private WsMessageHeaderType wsMessageHeaderField;

        private System.Threading.SendOrPostCallback QueryPortMessageOperationCompleted;

        private System.Threading.SendOrPostCallback ReplyPortOutRequestOperationCompleted;

        private System.Threading.SendOrPostCallback ResendPortMessageOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public WholesalePortMessageService()
        {
            this.Url = global::SprintWseLibrary.Properties.Settings.Default.PingTestClient_com_sprint_WholesalePortMessageService_WholesalePortMessageService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public WsMessageHeaderType wsMessageHeader
        {
            get
            {
                return this.wsMessageHeaderField;
            }
            set
            {
                this.wsMessageHeaderField = value;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event QueryPortMessageCompletedEventHandler QueryPortMessageCompleted;

        /// <remarks/>
        public event ReplyPortOutRequestCompletedEventHandler ReplyPortOutRequestCompleted;

        /// <remarks/>
        public event ResendPortMessageCompletedEventHandler ResendPortMessageCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("wsMessageHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("QueryPortMessage", RequestElementName = "queryPortMessage", RequestNamespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
            "", ResponseElementName = "queryPortMessageResponse", ResponseNamespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
            "", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("wholesalePortMessageList")]
        public WholesalePortMessageListType QueryPortMessage(QueryPortMessageListType queryPortMessageInfo)
        {
            object[] results = this.Invoke("QueryPortMessage", new object[] {
                        queryPortMessageInfo});
            return ((WholesalePortMessageListType)(results[0]));
        }

        /// <remarks/>
        public void QueryPortMessageAsync(QueryPortMessageListType queryPortMessageInfo)
        {
            this.QueryPortMessageAsync(queryPortMessageInfo, null);
        }

        /// <remarks/>
        public void QueryPortMessageAsync(QueryPortMessageListType queryPortMessageInfo, object userState)
        {
            if ((this.QueryPortMessageOperationCompleted == null))
            {
                this.QueryPortMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQueryPortMessageOperationCompleted);
            }
            this.InvokeAsync("QueryPortMessage", new object[] {
                        queryPortMessageInfo}, this.QueryPortMessageOperationCompleted, userState);
        }

        private void OnQueryPortMessageOperationCompleted(object arg)
        {
            if ((this.QueryPortMessageCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QueryPortMessageCompleted(this, new QueryPortMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("wsMessageHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ReplyPortOutRequest", RequestElementName = "replyPortOutRequest", RequestNamespace = "http://integration.sprint.com/interfaces/replyPortOutRequest/v1/replyPortOutReque" +
            "st.xsd", ResponseElementName = "replyPortOutRequestResponse", ResponseNamespace = "http://integration.sprint.com/interfaces/replyPortOutRequest/v1/replyPortOutReque" +
            "st.xsd", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ReplyPortOutRequest(string messageId, string portId, string mdn, PortResponseTypeCode1 responseType, SupplementalMessageTypeIdentifier1 supplementalCode, [System.Xml.Serialization.XmlIgnoreAttribute()] bool supplementalCodeSpecified, ImplementationPartnerInfoType1 implementationPartnerInfo, System.DateTime dueDateTime, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dueDateTimeSpecified, string reasonCode, string reasonDesc, string remarks, PortDelayCode1 delayCode, [System.Xml.Serialization.XmlIgnoreAttribute()] bool delayCodeSpecified)
        {
            this.Invoke("ReplyPortOutRequest", new object[] {
                        messageId,
                        portId,
                        mdn,
                        responseType,
                        supplementalCode,
                        supplementalCodeSpecified,
                        implementationPartnerInfo,
                        dueDateTime,
                        dueDateTimeSpecified,
                        reasonCode,
                        reasonDesc,
                        remarks,
                        delayCode,
                        delayCodeSpecified});
        }

        /// <remarks/>
        public void ReplyPortOutRequestAsync(string messageId, string portId, string mdn, PortResponseTypeCode1 responseType, SupplementalMessageTypeIdentifier1 supplementalCode, bool supplementalCodeSpecified, ImplementationPartnerInfoType1 implementationPartnerInfo, System.DateTime dueDateTime, bool dueDateTimeSpecified, string reasonCode, string reasonDesc, string remarks, PortDelayCode1 delayCode, bool delayCodeSpecified)
        {
            this.ReplyPortOutRequestAsync(messageId, portId, mdn, responseType, supplementalCode, supplementalCodeSpecified, implementationPartnerInfo, dueDateTime, dueDateTimeSpecified, reasonCode, reasonDesc, remarks, delayCode, delayCodeSpecified, null);
        }

        /// <remarks/>
        public void ReplyPortOutRequestAsync(string messageId, string portId, string mdn, PortResponseTypeCode1 responseType, SupplementalMessageTypeIdentifier1 supplementalCode, bool supplementalCodeSpecified, ImplementationPartnerInfoType1 implementationPartnerInfo, System.DateTime dueDateTime, bool dueDateTimeSpecified, string reasonCode, string reasonDesc, string remarks, PortDelayCode1 delayCode, bool delayCodeSpecified, object userState)
        {
            if ((this.ReplyPortOutRequestOperationCompleted == null))
            {
                this.ReplyPortOutRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReplyPortOutRequestOperationCompleted);
            }
            this.InvokeAsync("ReplyPortOutRequest", new object[] {
                        messageId,
                        portId,
                        mdn,
                        responseType,
                        supplementalCode,
                        supplementalCodeSpecified,
                        implementationPartnerInfo,
                        dueDateTime,
                        dueDateTimeSpecified,
                        reasonCode,
                        reasonDesc,
                        remarks,
                        delayCode,
                        delayCodeSpecified}, this.ReplyPortOutRequestOperationCompleted, userState);
        }

        private void OnReplyPortOutRequestOperationCompleted(object arg)
        {
            if ((this.ReplyPortOutRequestCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReplyPortOutRequestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("wsMessageHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("ResendPortMessage", RequestElementName = "resendPortMessage", RequestNamespace = "http://integration.sprint.com/interfaces/resendPortMessage/v1/resendPortMessage.x" +
            "sd", ResponseElementName = "resendPortMessageResponse", ResponseNamespace = "http://integration.sprint.com/interfaces/resendPortMessage/v1/resendPortMessage.x" +
            "sd", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("totalPossibleRecords", DataType = "integer")]
        public string ResendPortMessage([System.Xml.Serialization.XmlArrayItemAttribute("resendPortMessageInfo", IsNullable = false)] ResendPortMessageInfoType[] resendPortMessageInfoList)
        {
            object[] results = this.Invoke("ResendPortMessage", new object[] {
                        resendPortMessageInfoList});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void ResendPortMessageAsync(ResendPortMessageInfoType[] resendPortMessageInfoList)
        {
            this.ResendPortMessageAsync(resendPortMessageInfoList, null);
        }

        /// <remarks/>
        public void ResendPortMessageAsync(ResendPortMessageInfoType[] resendPortMessageInfoList, object userState)
        {
            if ((this.ResendPortMessageOperationCompleted == null))
            {
                this.ResendPortMessageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnResendPortMessageOperationCompleted);
            }
            this.InvokeAsync("ResendPortMessage", new object[] {
                        resendPortMessageInfoList}, this.ResendPortMessageOperationCompleted, userState);
        }

        private void OnResendPortMessageOperationCompleted(object arg)
        {
            if ((this.ResendPortMessageCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ResendPortMessageCompleted(this, new ResendPortMessageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    [System.Xml.Serialization.XmlRootAttribute("wsMessageHeader", Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2", IsNullable = false)]
    public partial class WsMessageHeaderType : System.Web.Services.Protocols.SoapHeader
    {

        private TrackingMessageHeaderType trackingMessageHeaderField;

        private SecurityMessageHeaderType securityMessageHeaderField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public TrackingMessageHeaderType trackingMessageHeader
        {
            get
            {
                return this.trackingMessageHeaderField;
            }
            set
            {
                this.trackingMessageHeaderField = value;
            }
        }

        /// <remarks/>
        public SecurityMessageHeaderType securityMessageHeader
        {
            get
            {
                return this.securityMessageHeaderField;
            }
            set
            {
                this.securityMessageHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    public partial class TrackingMessageHeaderType
    {

        private string applicationIdField;

        private string applicationUserIdField;

        private string consumerIdField;

        private string messageIdField;

        private string conversationIdField;

        private string timeToLiveField;

        private long replyCompletionCodeField;

        private bool replyCompletionCodeFieldSpecified;

        private System.DateTime messageDateTimeStampField;

        /// <remarks/>
        public string applicationId
        {
            get
            {
                return this.applicationIdField;
            }
            set
            {
                this.applicationIdField = value;
            }
        }

        /// <remarks/>
        public string applicationUserId
        {
            get
            {
                return this.applicationUserIdField;
            }
            set
            {
                this.applicationUserIdField = value;
            }
        }

        /// <remarks/>
        public string consumerId
        {
            get
            {
                return this.consumerIdField;
            }
            set
            {
                this.consumerIdField = value;
            }
        }

        /// <remarks/>
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        public string conversationId
        {
            get
            {
                return this.conversationIdField;
            }
            set
            {
                this.conversationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string timeToLive
        {
            get
            {
                return this.timeToLiveField;
            }
            set
            {
                this.timeToLiveField = value;
            }
        }

        /// <remarks/>
        public long replyCompletionCode
        {
            get
            {
                return this.replyCompletionCodeField;
            }
            set
            {
                this.replyCompletionCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool replyCompletionCodeSpecified
        {
            get
            {
                return this.replyCompletionCodeFieldSpecified;
            }
            set
            {
                this.replyCompletionCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime messageDateTimeStamp
        {
            get
            {
                return this.messageDateTimeStampField;
            }
            set
            {
                this.messageDateTimeStampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "DateRangeInfoType", Namespace = "http://integration.sprint.com/interfaces/resendPortMessage/v1/resendPortMessage.x" +
        "sd")]
    public partial class DateRangeInfoType1
    {

        private System.DateTime fromDateField;

        private System.DateTime toDateField;

        /// <remarks/>
        public System.DateTime fromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }

        /// <remarks/>
        public System.DateTime toDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/resendPortMessage/v1/resendPortMessage.x" +
        "sd")]
    public partial class ResendPortMessageInfoType
    {

        private string messageIdField;

        private string mdnField;

        private PortMessageTypeCode1 messageTypeCodeField;

        private bool messageTypeCodeFieldSpecified;

        private MessageStatusCodeType1 messageStatusCodeField;

        private bool messageStatusCodeFieldSpecified;

        private DateRangeInfoType1 dateRangeInfoField;

        /// <remarks/>
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        public string mdn
        {
            get
            {
                return this.mdnField;
            }
            set
            {
                this.mdnField = value;
            }
        }

        /// <remarks/>
        public PortMessageTypeCode1 messageTypeCode
        {
            get
            {
                return this.messageTypeCodeField;
            }
            set
            {
                this.messageTypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messageTypeCodeSpecified
        {
            get
            {
                return this.messageTypeCodeFieldSpecified;
            }
            set
            {
                this.messageTypeCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public MessageStatusCodeType1 messageStatusCode
        {
            get
            {
                return this.messageStatusCodeField;
            }
            set
            {
                this.messageStatusCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messageStatusCodeSpecified
        {
            get
            {
                return this.messageStatusCodeFieldSpecified;
            }
            set
            {
                this.messageStatusCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public DateRangeInfoType1 dateRangeInfo
        {
            get
            {
                return this.dateRangeInfoField;
            }
            set
            {
                this.dateRangeInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "PortMessageTypeCode", Namespace = "http://integration.sprint.com/interfaces/resendPortMessage/v1/resendPortMessage.x" +
        "sd")]
    public enum PortMessageTypeCode1
    {

        /// <remarks/>
        POR,

        /// <remarks/>
        DDT,

        /// <remarks/>
        PIR,

        /// <remarks/>
        PTS,

        /// <remarks/>
        PTA,

        /// <remarks/>
        PTN,

        /// <remarks/>
        PTC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "MessageStatusCodeType", Namespace = "http://integration.sprint.com/interfaces/resendPortMessage/v1/resendPortMessage.x" +
        "sd")]
    public enum MessageStatusCodeType1
    {

        /// <remarks/>
        M,

        /// <remarks/>
        S,

        /// <remarks/>
        F,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "ImplementationPartnerInfoType", Namespace = "http://integration.sprint.com/interfaces/replyPortOutRequest/v1/replyPortOutReque" +
        "st.xsd")]
    public partial class ImplementationPartnerInfoType1
    {

        private string contactNameField;

        private string contactPhoneField;

        /// <remarks/>
        public string contactName
        {
            get
            {
                return this.contactNameField;
            }
            set
            {
                this.contactNameField = value;
            }
        }

        /// <remarks/>
        public string contactPhone
        {
            get
            {
                return this.contactPhoneField;
            }
            set
            {
                this.contactPhoneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class ActivityRecordInfoType
    {

        private string applIdField;

        private MessageStatus messageActivityDescField;

        private System.DateTime initialActivityDateTimeField;

        private System.DateTime dateStampField;

        /// <remarks/>
        public string applId
        {
            get
            {
                return this.applIdField;
            }
            set
            {
                this.applIdField = value;
            }
        }

        /// <remarks/>
        public MessageStatus messageActivityDesc
        {
            get
            {
                return this.messageActivityDescField;
            }
            set
            {
                this.messageActivityDescField = value;
            }
        }

        /// <remarks/>
        public System.DateTime initialActivityDateTime
        {
            get
            {
                return this.initialActivityDateTimeField;
            }
            set
            {
                this.initialActivityDateTimeField = value;
            }
        }

        /// <remarks/>
        public System.DateTime dateStamp
        {
            get
            {
                return this.dateStampField;
            }
            set
            {
                this.dateStampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public enum MessageStatus
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Message Stored")]
        MessageStored,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Message Queried")]
        MessageQueried,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Send Failed")]
        SendFailed,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Send Successful")]
        SendSuccessful,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class DueDateTimeChangesInfoType
    {

        private System.DateTime originalDueDateTimeField;

        private bool originalDueDateTimeFieldSpecified;

        private System.DateTime revisedDueDateTimeField;

        private bool revisedDueDateTimeFieldSpecified;

        /// <remarks/>
        public System.DateTime originalDueDateTime
        {
            get
            {
                return this.originalDueDateTimeField;
            }
            set
            {
                this.originalDueDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool originalDueDateTimeSpecified
        {
            get
            {
                return this.originalDueDateTimeFieldSpecified;
            }
            set
            {
                this.originalDueDateTimeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime revisedDueDateTime
        {
            get
            {
                return this.revisedDueDateTimeField;
            }
            set
            {
                this.revisedDueDateTimeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool revisedDueDateTimeSpecified
        {
            get
            {
                return this.revisedDueDateTimeFieldSpecified;
            }
            set
            {
                this.revisedDueDateTimeFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class PortDueDateTimeInfoType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dueDateTime", typeof(System.DateTime))]
        [System.Xml.Serialization.XmlElementAttribute("dueDateTimeChangesInfo", typeof(DueDateTimeChangesInfoType))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class ImplementationPartnerInfoType
    {

        private string contactNameField;

        private string contactPhoneField;

        /// <remarks/>
        public string contactName
        {
            get
            {
                return this.contactNameField;
            }
            set
            {
                this.contactNameField = value;
            }
        }

        /// <remarks/>
        public string contactPhone
        {
            get
            {
                return this.contactPhoneField;
            }
            set
            {
                this.contactPhoneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class NetworkServiceProviderInfoType
    {

        private string networkServiceProviderIdField;

        private string localServiceProviderIdField;

        private string serviceProviderNameField;

        /// <remarks/>
        public string networkServiceProviderId
        {
            get
            {
                return this.networkServiceProviderIdField;
            }
            set
            {
                this.networkServiceProviderIdField = value;
            }
        }

        /// <remarks/>
        public string localServiceProviderId
        {
            get
            {
                return this.localServiceProviderIdField;
            }
            set
            {
                this.localServiceProviderIdField = value;
            }
        }

        /// <remarks/>
        public string serviceProviderName
        {
            get
            {
                return this.serviceProviderNameField;
            }
            set
            {
                this.serviceProviderNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class SsnTaxIdChoiceTypeType
    {

        private string itemField;

        private ItemChoiceType itemElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ssn", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("taxId", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "", IncludeInSchema = false)]
    public enum ItemChoiceType
    {

        /// <remarks/>
        ssn,

        /// <remarks/>
        taxId,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class BillingAddressInfoType
    {

        private string streetNumberField;

        private string streetNameField;

        private string streetDirectionIndField;

        private string cityField;

        private string stateField;

        private string zipCodeField;

        private string countryField;

        /// <remarks/>
        public string streetNumber
        {
            get
            {
                return this.streetNumberField;
            }
            set
            {
                this.streetNumberField = value;
            }
        }

        /// <remarks/>
        public string streetName
        {
            get
            {
                return this.streetNameField;
            }
            set
            {
                this.streetNameField = value;
            }
        }

        /// <remarks/>
        public string streetDirectionInd
        {
            get
            {
                return this.streetDirectionIndField;
            }
            set
            {
                this.streetDirectionIndField = value;
            }
        }

        /// <remarks/>
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string state
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public string zipCode
        {
            get
            {
                return this.zipCodeField;
            }
            set
            {
                this.zipCodeField = value;
            }
        }

        /// <remarks/>
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class BillBusinessNameType
    {

        private string businessNameField;

        /// <remarks/>
        public string businessName
        {
            get
            {
                return this.businessNameField;
            }
            set
            {
                this.businessNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class BillCustomerNameType
    {

        private string firstNameField;

        private string middleInitialField;

        private string billLastNameField;

        /// <remarks/>
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        public string middleInitial
        {
            get
            {
                return this.middleInitialField;
            }
            set
            {
                this.middleInitialField = value;
            }
        }

        /// <remarks/>
        public string billLastName
        {
            get
            {
                return this.billLastNameField;
            }
            set
            {
                this.billLastNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class CustomerBusinessNameType
    {

        private BillCustomerNameType customerNameInfoField;

        private BillBusinessNameType businessNameInfoField;

        /// <remarks/>
        public BillCustomerNameType customerNameInfo
        {
            get
            {
                return this.customerNameInfoField;
            }
            set
            {
                this.customerNameInfoField = value;
            }
        }

        /// <remarks/>
        public BillBusinessNameType businessNameInfo
        {
            get
            {
                return this.businessNameInfoField;
            }
            set
            {
                this.businessNameInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class BillingNameInfoType
    {

        private string billPrefixNameField;

        private CustomerBusinessNameType nameInfoField;

        private string suffixNameField;

        /// <remarks/>
        public string billPrefixName
        {
            get
            {
                return this.billPrefixNameField;
            }
            set
            {
                this.billPrefixNameField = value;
            }
        }

        /// <remarks/>
        public CustomerBusinessNameType nameInfo
        {
            get
            {
                return this.nameInfoField;
            }
            set
            {
                this.nameInfoField = value;
            }
        }

        /// <remarks/>
        public string suffixName
        {
            get
            {
                return this.suffixNameField;
            }
            set
            {
                this.suffixNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class PortResellerPartnerInfoType
    {

        private string portInResellerPartnerIdField;

        private string portOutResellerPartnerIdField;

        /// <remarks/>
        public string portInResellerPartnerId
        {
            get
            {
                return this.portInResellerPartnerIdField;
            }
            set
            {
                this.portInResellerPartnerIdField = value;
            }
        }

        /// <remarks/>
        public string portOutResellerPartnerId
        {
            get
            {
                return this.portOutResellerPartnerIdField;
            }
            set
            {
                this.portOutResellerPartnerIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class ResellerPartnerIdInfoType
    {

        private object itemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("portResellerPartnerInfo", typeof(PortResellerPartnerInfoType))]
        [System.Xml.Serialization.XmlElementAttribute("resellerPartnerId", typeof(string))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class WholesalePortMessageTypeInfoType
    {

        private string messageIdField;

        private PortMessageTypeCode messageTypeCodeField;

        private PortMessageTypeDescription messageTypeDescField;

        private MessageActivityCode messageStatusCodeField;

        private MessageStatus messageStatusDescField;

        private string mdnField;

        private string portIdField;

        private string portRequestNumberField;

        private ResellerPartnerIdInfoType resellerPartnerIdInfoField;

        private SupplementalMessageTypeIdentifier supplementalCodeField;

        private bool supplementalCodeFieldSpecified;

        private BillingNameInfoType billingNameInfoField;

        private BillingAddressInfoType billAddressInfoField;

        private SsnTaxIdChoiceTypeType ssnTaxIdInfoField;

        private string ospBanField;

        private string passwordPinField;

        private string remarksField;

        private NetworkServiceProviderInfoType newNetWorkServiceProviderInfoField;

        private NetworkServiceProviderInfoType oldNetWorkServiceProviderInfoField;

        private ImplementationPartnerInfoType implementationPartnerInfoField;

        private PortDueDateTimeInfoType portDueDateTimeInfoField;

        private PortResponseTypeCode responseTypeField;

        private bool responseTypeFieldSpecified;

        private string reasonCodeField;

        private string reasonTextField;

        private PortDelayCode delayCodeField;

        private bool delayCodeFieldSpecified;

        private string messageCodeField;

        private string messageTextField;

        private PortActionTypeCode actionCodeField;

        private bool actionCodeFieldSpecified;

        private ActivityRecordInfoType[] activityRecordListField;

        private SendAutoRejectTypeCode autoRejectStatusField;

        private bool autoRejectStatusFieldSpecified;

        private ReplyPortOutRequestCode replyPortOutRequestStatusField;

        private bool replyPortOutRequestStatusFieldSpecified;

        private string portCancelIndField;

        private System.DateTime messageCreationTimeField;

        /// <remarks/>
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        public PortMessageTypeCode messageTypeCode
        {
            get
            {
                return this.messageTypeCodeField;
            }
            set
            {
                this.messageTypeCodeField = value;
            }
        }

        /// <remarks/>
        public PortMessageTypeDescription messageTypeDesc
        {
            get
            {
                return this.messageTypeDescField;
            }
            set
            {
                this.messageTypeDescField = value;
            }
        }

        /// <remarks/>
        public MessageActivityCode messageStatusCode
        {
            get
            {
                return this.messageStatusCodeField;
            }
            set
            {
                this.messageStatusCodeField = value;
            }
        }

        /// <remarks/>
        public MessageStatus messageStatusDesc
        {
            get
            {
                return this.messageStatusDescField;
            }
            set
            {
                this.messageStatusDescField = value;
            }
        }

        /// <remarks/>
        public string mdn
        {
            get
            {
                return this.mdnField;
            }
            set
            {
                this.mdnField = value;
            }
        }

        /// <remarks/>
        public string portId
        {
            get
            {
                return this.portIdField;
            }
            set
            {
                this.portIdField = value;
            }
        }

        /// <remarks/>
        public string portRequestNumber
        {
            get
            {
                return this.portRequestNumberField;
            }
            set
            {
                this.portRequestNumberField = value;
            }
        }

        /// <remarks/>
        public ResellerPartnerIdInfoType resellerPartnerIdInfo
        {
            get
            {
                return this.resellerPartnerIdInfoField;
            }
            set
            {
                this.resellerPartnerIdInfoField = value;
            }
        }

        /// <remarks/>
        public SupplementalMessageTypeIdentifier supplementalCode
        {
            get
            {
                return this.supplementalCodeField;
            }
            set
            {
                this.supplementalCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool supplementalCodeSpecified
        {
            get
            {
                return this.supplementalCodeFieldSpecified;
            }
            set
            {
                this.supplementalCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public BillingNameInfoType billingNameInfo
        {
            get
            {
                return this.billingNameInfoField;
            }
            set
            {
                this.billingNameInfoField = value;
            }
        }

        /// <remarks/>
        public BillingAddressInfoType billAddressInfo
        {
            get
            {
                return this.billAddressInfoField;
            }
            set
            {
                this.billAddressInfoField = value;
            }
        }

        /// <remarks/>
        public SsnTaxIdChoiceTypeType ssnTaxIdInfo
        {
            get
            {
                return this.ssnTaxIdInfoField;
            }
            set
            {
                this.ssnTaxIdInfoField = value;
            }
        }

        /// <remarks/>
        public string ospBan
        {
            get
            {
                return this.ospBanField;
            }
            set
            {
                this.ospBanField = value;
            }
        }

        /// <remarks/>
        public string passwordPin
        {
            get
            {
                return this.passwordPinField;
            }
            set
            {
                this.passwordPinField = value;
            }
        }

        /// <remarks/>
        public string remarks
        {
            get
            {
                return this.remarksField;
            }
            set
            {
                this.remarksField = value;
            }
        }

        /// <remarks/>
        public NetworkServiceProviderInfoType newNetWorkServiceProviderInfo
        {
            get
            {
                return this.newNetWorkServiceProviderInfoField;
            }
            set
            {
                this.newNetWorkServiceProviderInfoField = value;
            }
        }

        /// <remarks/>
        public NetworkServiceProviderInfoType oldNetWorkServiceProviderInfo
        {
            get
            {
                return this.oldNetWorkServiceProviderInfoField;
            }
            set
            {
                this.oldNetWorkServiceProviderInfoField = value;
            }
        }

        /// <remarks/>
        public ImplementationPartnerInfoType implementationPartnerInfo
        {
            get
            {
                return this.implementationPartnerInfoField;
            }
            set
            {
                this.implementationPartnerInfoField = value;
            }
        }

        /// <remarks/>
        public PortDueDateTimeInfoType portDueDateTimeInfo
        {
            get
            {
                return this.portDueDateTimeInfoField;
            }
            set
            {
                this.portDueDateTimeInfoField = value;
            }
        }

        /// <remarks/>
        public PortResponseTypeCode responseType
        {
            get
            {
                return this.responseTypeField;
            }
            set
            {
                this.responseTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool responseTypeSpecified
        {
            get
            {
                return this.responseTypeFieldSpecified;
            }
            set
            {
                this.responseTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string reasonCode
        {
            get
            {
                return this.reasonCodeField;
            }
            set
            {
                this.reasonCodeField = value;
            }
        }

        /// <remarks/>
        public string reasonText
        {
            get
            {
                return this.reasonTextField;
            }
            set
            {
                this.reasonTextField = value;
            }
        }

        /// <remarks/>
        public PortDelayCode delayCode
        {
            get
            {
                return this.delayCodeField;
            }
            set
            {
                this.delayCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool delayCodeSpecified
        {
            get
            {
                return this.delayCodeFieldSpecified;
            }
            set
            {
                this.delayCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string messageCode
        {
            get
            {
                return this.messageCodeField;
            }
            set
            {
                this.messageCodeField = value;
            }
        }

        /// <remarks/>
        public string messageText
        {
            get
            {
                return this.messageTextField;
            }
            set
            {
                this.messageTextField = value;
            }
        }

        /// <remarks/>
        public PortActionTypeCode actionCode
        {
            get
            {
                return this.actionCodeField;
            }
            set
            {
                this.actionCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actionCodeSpecified
        {
            get
            {
                return this.actionCodeFieldSpecified;
            }
            set
            {
                this.actionCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("activityRecordInfo", IsNullable = false)]
        public ActivityRecordInfoType[] activityRecordList
        {
            get
            {
                return this.activityRecordListField;
            }
            set
            {
                this.activityRecordListField = value;
            }
        }

        /// <remarks/>
        public SendAutoRejectTypeCode autoRejectStatus
        {
            get
            {
                return this.autoRejectStatusField;
            }
            set
            {
                this.autoRejectStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool autoRejectStatusSpecified
        {
            get
            {
                return this.autoRejectStatusFieldSpecified;
            }
            set
            {
                this.autoRejectStatusFieldSpecified = value;
            }
        }

        /// <remarks/>
        public ReplyPortOutRequestCode replyPortOutRequestStatus
        {
            get
            {
                return this.replyPortOutRequestStatusField;
            }
            set
            {
                this.replyPortOutRequestStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool replyPortOutRequestStatusSpecified
        {
            get
            {
                return this.replyPortOutRequestStatusFieldSpecified;
            }
            set
            {
                this.replyPortOutRequestStatusFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string portCancelInd
        {
            get
            {
                return this.portCancelIndField;
            }
            set
            {
                this.portCancelIndField = value;
            }
        }

        /// <remarks/>
        public System.DateTime messageCreationTime
        {
            get
            {
                return this.messageCreationTimeField;
            }
            set
            {
                this.messageCreationTimeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public enum PortMessageTypeCode
    {

        /// <remarks/>
        POR,

        /// <remarks/>
        DDT,

        /// <remarks/>
        PIR,

        /// <remarks/>
        PTS,

        /// <remarks/>
        PTA,

        /// <remarks/>
        PTN,

        /// <remarks/>
        PTC,

        /// <remarks/>
        RPR,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public enum PortMessageTypeDescription
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PortOut Request")]
        PortOutRequest,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Due Date and Time")]
        DueDateandTime,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("PortIn Response")]
        PortInResponse,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Port Status")]
        PortStatus,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Port Abandonment")]
        PortAbandonment,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Port Notification")]
        PortNotification,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Port Cancellation")]
        PortCancellation,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Reply PortOut Request")]
        ReplyPortOutRequest,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public enum MessageActivityCode
    {

        /// <remarks/>
        M,

        /// <remarks/>
        S,

        /// <remarks/>
        F,

        /// <remarks/>
        Q,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public enum SupplementalMessageTypeIdentifier
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public enum PortResponseTypeCode
    {

        /// <remarks/>
        C,

        /// <remarks/>
        D,

        /// <remarks/>
        R,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public enum PortDelayCode
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6G")]
        Item6G,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6H")]
        Item6H,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6J")]
        Item6J,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6L")]
        Item6L,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public enum PortActionTypeCode
    {

        /// <remarks/>
        ACT,

        /// <remarks/>
        DAC,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public enum SendAutoRejectTypeCode
    {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public enum ReplyPortOutRequestCode
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class WholesalePortMessageListType
    {

        private bool areMoreRecordsField;

        private string lastSequenceNumberField;

        private WholesalePortMessageTypeInfoType[] wholesalePortMessageTypeListField;

        /// <remarks/>
        public bool areMoreRecords
        {
            get
            {
                return this.areMoreRecordsField;
            }
            set
            {
                this.areMoreRecordsField = value;
            }
        }

        /// <remarks/>
        public string lastSequenceNumber
        {
            get
            {
                return this.lastSequenceNumberField;
            }
            set
            {
                this.lastSequenceNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("wholesalePortMessageTypeInfo", IsNullable = false)]
        public WholesalePortMessageTypeInfoType[] wholesalePortMessageTypeList
        {
            get
            {
                return this.wholesalePortMessageTypeListField;
            }
            set
            {
                this.wholesalePortMessageTypeListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class DateRangeInfoType
    {

        private System.DateTime fromDateField;

        private System.DateTime toDateField;

        /// <remarks/>
        public System.DateTime fromDate
        {
            get
            {
                return this.fromDateField;
            }
            set
            {
                this.fromDateField = value;
            }
        }

        /// <remarks/>
        public System.DateTime toDate
        {
            get
            {
                return this.toDateField;
            }
            set
            {
                this.toDateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public partial class QueryPortMessageListType
    {

        private string mdnField;

        private string messageIdField;

        private PortMessageTypeCode messageTypeCodeField;

        private bool messageTypeCodeFieldSpecified;

        private MessageStatusCodeType messageStatusCodeField;

        private bool messageStatusCodeFieldSpecified;

        private MessageActivityCode recentMessageActivityCodeField;

        private bool recentMessageActivityCodeFieldSpecified;

        private DateRangeInfoType dateRangeInfoField;

        private PortOutRespondedTypeCode replyPortOutRequestStatusField;

        private bool replyPortOutRequestStatusFieldSpecified;

        private QueryPortMessageListTypePortCancelInd portCancelIndField;

        private bool portCancelIndFieldSpecified;

        private SendAutoRejectTypeCode autoRejectStatusField;

        private bool autoRejectStatusFieldSpecified;

        private string lastSequenceNumberField;

        private bool activityListIndField;

        private bool activityListIndFieldSpecified;

        /// <remarks/>
        public string mdn
        {
            get
            {
                return this.mdnField;
            }
            set
            {
                this.mdnField = value;
            }
        }

        /// <remarks/>
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        public PortMessageTypeCode messageTypeCode
        {
            get
            {
                return this.messageTypeCodeField;
            }
            set
            {
                this.messageTypeCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messageTypeCodeSpecified
        {
            get
            {
                return this.messageTypeCodeFieldSpecified;
            }
            set
            {
                this.messageTypeCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public MessageStatusCodeType messageStatusCode
        {
            get
            {
                return this.messageStatusCodeField;
            }
            set
            {
                this.messageStatusCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool messageStatusCodeSpecified
        {
            get
            {
                return this.messageStatusCodeFieldSpecified;
            }
            set
            {
                this.messageStatusCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public MessageActivityCode recentMessageActivityCode
        {
            get
            {
                return this.recentMessageActivityCodeField;
            }
            set
            {
                this.recentMessageActivityCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool recentMessageActivityCodeSpecified
        {
            get
            {
                return this.recentMessageActivityCodeFieldSpecified;
            }
            set
            {
                this.recentMessageActivityCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public DateRangeInfoType dateRangeInfo
        {
            get
            {
                return this.dateRangeInfoField;
            }
            set
            {
                this.dateRangeInfoField = value;
            }
        }

        /// <remarks/>
        public PortOutRespondedTypeCode replyPortOutRequestStatus
        {
            get
            {
                return this.replyPortOutRequestStatusField;
            }
            set
            {
                this.replyPortOutRequestStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool replyPortOutRequestStatusSpecified
        {
            get
            {
                return this.replyPortOutRequestStatusFieldSpecified;
            }
            set
            {
                this.replyPortOutRequestStatusFieldSpecified = value;
            }
        }

        /// <remarks/>
        public QueryPortMessageListTypePortCancelInd portCancelInd
        {
            get
            {
                return this.portCancelIndField;
            }
            set
            {
                this.portCancelIndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool portCancelIndSpecified
        {
            get
            {
                return this.portCancelIndFieldSpecified;
            }
            set
            {
                this.portCancelIndFieldSpecified = value;
            }
        }

        /// <remarks/>
        public SendAutoRejectTypeCode autoRejectStatus
        {
            get
            {
                return this.autoRejectStatusField;
            }
            set
            {
                this.autoRejectStatusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool autoRejectStatusSpecified
        {
            get
            {
                return this.autoRejectStatusFieldSpecified;
            }
            set
            {
                this.autoRejectStatusFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string lastSequenceNumber
        {
            get
            {
                return this.lastSequenceNumberField;
            }
            set
            {
                this.lastSequenceNumberField = value;
            }
        }

        /// <remarks/>
        public bool activityListInd
        {
            get
            {
                return this.activityListIndField;
            }
            set
            {
                this.activityListIndField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activityListIndSpecified
        {
            get
            {
                return this.activityListIndFieldSpecified;
            }
            set
            {
                this.activityListIndFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public enum MessageStatusCodeType
    {

        /// <remarks/>
        M,

        /// <remarks/>
        S,

        /// <remarks/>
        F,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public enum PortOutRespondedTypeCode
    {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("")]
        Item,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://integration.sprint.com/interfaces/queryPortMessage/v1/queryPortMessage.xsd" +
        "")]
    public enum QueryPortMessageListTypePortCancelInd
    {

        /// <remarks/>
        Y,

        /// <remarks/>
        N,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    public partial class BasicCredentialInfoType
    {

        private string idField;

        private string passwordField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    public partial class SdcLoginCredentialsType
    {

        private string userIdField;

        private string passwordField;

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    public partial class SecurityMessageHeaderType
    {

        private object itemField;

        private string corpIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("basicCredentialInfo", typeof(BasicCredentialInfoType))]
        [System.Xml.Serialization.XmlElementAttribute("pin", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("sdcLoginCredentials", typeof(SdcLoginCredentialsType))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public string corpId
        {
            get
            {
                return this.corpIdField;
            }
            set
            {
                this.corpIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "PortResponseTypeCode", Namespace = "http://integration.sprint.com/interfaces/replyPortOutRequest/v1/replyPortOutReque" +
        "st.xsd")]
    public enum PortResponseTypeCode1
    {

        /// <remarks/>
        C,

        /// <remarks/>
        D,

        /// <remarks/>
        R,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "SupplementalMessageTypeIdentifier", Namespace = "http://integration.sprint.com/interfaces/replyPortOutRequest/v1/replyPortOutReque" +
        "st.xsd")]
    public enum SupplementalMessageTypeIdentifier1
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName = "PortDelayCode", Namespace = "http://integration.sprint.com/interfaces/replyPortOutRequest/v1/replyPortOutReque" +
        "st.xsd")]
    public enum PortDelayCode1
    {

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6G")]
        Item6G,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6H")]
        Item6H,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6J")]
        Item6J,

        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("6L")]
        Item6L,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void QueryPortMessageCompletedEventHandler(object sender, QueryPortMessageCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QueryPortMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal QueryPortMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WholesalePortMessageListType Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WholesalePortMessageListType)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ReplyPortOutRequestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ResendPortMessageCompletedEventHandler(object sender, ResendPortMessageCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ResendPortMessageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ResendPortMessageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591