//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.4952.
// 
#pragma warning disable 1591

namespace SprintWseLibrary.com.sprint.WholesaleSubscriptionModifyService
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;



    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "WholesaleSubscriptionModifyBinding", Namespace = "http://integration.sprint.com/eai/services/WholesaleSubscriptionModify/v1/Wholesa" +
        "leSubscriptionModify.wsdl")]
    public partial class WholesaleSubscriptionModifyService : Microsoft.Web.Services3.WebServicesClientProtocol
    {

        private WsMessageHeaderType wsMessageHeaderField;

        private System.Threading.SendOrPostCallback ChangeServicePlansOperationCompleted;

        private System.Threading.SendOrPostCallback ExpireSubscriptionOperationCompleted;

        private System.Threading.SendOrPostCallback RestoreSubscriptionOperationCompleted;

        private System.Threading.SendOrPostCallback SuspendSubscriptionOperationCompleted;

        private System.Threading.SendOrPostCallback WholesaleChangeServicePlansV2OperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public WholesaleSubscriptionModifyService()
        {
            this.Url = global::SprintWseLibrary.Properties.Settings.Default.PingTestClient_com_sprint_WholesaleSubscriptionModifyService_WholesaleSubscriptionModifyService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public WsMessageHeaderType wsMessageHeader
        {
            get
            {
                return this.wsMessageHeaderField;
            }
            set
            {
                this.wsMessageHeaderField = value;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event ChangeServicePlansCompletedEventHandler ChangeServicePlansCompleted;

        /// <remarks/>
        public event ExpireSubscriptionCompletedEventHandler ExpireSubscriptionCompleted;

        /// <remarks/>
        public event RestoreSubscriptionCompletedEventHandler RestoreSubscriptionCompleted;

        /// <remarks/>
        public event SuspendSubscriptionCompletedEventHandler SuspendSubscriptionCompleted;

        /// <remarks/>
        public event WholesaleChangeServicePlansV2CompletedEventHandler WholesaleChangeServicePlansV2Completed;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("wsMessageHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("changeServicePlans", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("changeServicePlansResponse", Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
            "scriptionEnvelope.xsd")]
        public ConfirmMsg ChangeServicePlans([System.Xml.Serialization.XmlElementAttribute("changeServicePlans", Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
            "scriptionEnvelope.xsd")] ChangeServicePlansRequest changeServicePlans1)
        {
            object[] results = this.Invoke("ChangeServicePlans", new object[] {
                        changeServicePlans1});
            return ((ConfirmMsg)(results[0]));
        }

        /// <remarks/>
        public void ChangeServicePlansAsync(ChangeServicePlansRequest changeServicePlans1)
        {
            this.ChangeServicePlansAsync(changeServicePlans1, null);
        }

        /// <remarks/>
        public void ChangeServicePlansAsync(ChangeServicePlansRequest changeServicePlans1, object userState)
        {
            if ((this.ChangeServicePlansOperationCompleted == null))
            {
                this.ChangeServicePlansOperationCompleted = new System.Threading.SendOrPostCallback(this.OnChangeServicePlansOperationCompleted);
            }
            this.InvokeAsync("ChangeServicePlans", new object[] {
                        changeServicePlans1}, this.ChangeServicePlansOperationCompleted, userState);
        }

        private void OnChangeServicePlansOperationCompleted(object arg)
        {
            if ((this.ChangeServicePlansCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ChangeServicePlansCompleted(this, new ChangeServicePlansCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("wsMessageHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("expireSubscription", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("expireSubscriptionResponse", Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
            "scriptionEnvelope.xsd")]
        public ConfirmMsg ExpireSubscription([System.Xml.Serialization.XmlElementAttribute("expireSubscription", Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
            "scriptionEnvelope.xsd")] ExpireSubscriptionRequest expireSubscription1)
        {
            object[] results = this.Invoke("ExpireSubscription", new object[] {
                        expireSubscription1});
            return ((ConfirmMsg)(results[0]));
        }

        /// <remarks/>
        public void ExpireSubscriptionAsync(ExpireSubscriptionRequest expireSubscription1)
        {
            this.ExpireSubscriptionAsync(expireSubscription1, null);
        }

        /// <remarks/>
        public void ExpireSubscriptionAsync(ExpireSubscriptionRequest expireSubscription1, object userState)
        {
            if ((this.ExpireSubscriptionOperationCompleted == null))
            {
                this.ExpireSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnExpireSubscriptionOperationCompleted);
            }
            this.InvokeAsync("ExpireSubscription", new object[] {
                        expireSubscription1}, this.ExpireSubscriptionOperationCompleted, userState);
        }

        private void OnExpireSubscriptionOperationCompleted(object arg)
        {
            if ((this.ExpireSubscriptionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ExpireSubscriptionCompleted(this, new ExpireSubscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("wsMessageHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("restoreSubscription", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("restoreSubscriptionResponse", Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
            "scriptionEnvelope.xsd")]
        public ConfirmMsg RestoreSubscription([System.Xml.Serialization.XmlElementAttribute("restoreSubscription", Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
            "scriptionEnvelope.xsd")] RestoreSubscriptionRequest restoreSubscription1)
        {
            object[] results = this.Invoke("RestoreSubscription", new object[] {
                        restoreSubscription1});
            return ((ConfirmMsg)(results[0]));
        }

        /// <remarks/>
        public void RestoreSubscriptionAsync(RestoreSubscriptionRequest restoreSubscription1)
        {
            this.RestoreSubscriptionAsync(restoreSubscription1, null);
        }

        /// <remarks/>
        public void RestoreSubscriptionAsync(RestoreSubscriptionRequest restoreSubscription1, object userState)
        {
            if ((this.RestoreSubscriptionOperationCompleted == null))
            {
                this.RestoreSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRestoreSubscriptionOperationCompleted);
            }
            this.InvokeAsync("RestoreSubscription", new object[] {
                        restoreSubscription1}, this.RestoreSubscriptionOperationCompleted, userState);
        }

        private void OnRestoreSubscriptionOperationCompleted(object arg)
        {
            if ((this.RestoreSubscriptionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RestoreSubscriptionCompleted(this, new RestoreSubscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("wsMessageHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("suspendSubscription", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("suspendSubscriptionResponse", Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
            "scriptionEnvelope.xsd")]
        public ConfirmMsg SuspendSubscription([System.Xml.Serialization.XmlElementAttribute("suspendSubscription", Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
            "scriptionEnvelope.xsd")] SuspendSubscriptionRequest suspendSubscription1)
        {
            object[] results = this.Invoke("SuspendSubscription", new object[] {
                        suspendSubscription1});
            return ((ConfirmMsg)(results[0]));
        }

        /// <remarks/>
        public void SuspendSubscriptionAsync(SuspendSubscriptionRequest suspendSubscription1)
        {
            this.SuspendSubscriptionAsync(suspendSubscription1, null);
        }

        /// <remarks/>
        public void SuspendSubscriptionAsync(SuspendSubscriptionRequest suspendSubscription1, object userState)
        {
            if ((this.SuspendSubscriptionOperationCompleted == null))
            {
                this.SuspendSubscriptionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSuspendSubscriptionOperationCompleted);
            }
            this.InvokeAsync("SuspendSubscription", new object[] {
                        suspendSubscription1}, this.SuspendSubscriptionOperationCompleted, userState);
        }

        private void OnSuspendSubscriptionOperationCompleted(object arg)
        {
            if ((this.SuspendSubscriptionCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SuspendSubscriptionCompleted(this, new SuspendSubscriptionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("wsMessageHeader", Direction = System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("WholesaleChangeServicePlansV2", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("wholesaleChangeServicePlansV2Response", Namespace = "http://integration.sprint.com/interfaces/wholesaleChangeServicePlans/v2/wholesale" +
            "ChangeServicePlansV2.xsd")]
        public WholesaleChangeServicePlansV2RespnseType WholesaleChangeServicePlansV2([System.Xml.Serialization.XmlElementAttribute("wholesaleChangeServicePlansV2", Namespace = "http://integration.sprint.com/interfaces/wholesaleChangeServicePlans/v2/wholesale" +
            "ChangeServicePlansV2.xsd")] WholesaleChangeServicePlansV2Type wholesaleChangeServicePlansV21)
        {
            object[] results = this.Invoke("WholesaleChangeServicePlansV2", new object[] {
                        wholesaleChangeServicePlansV21});
            return ((WholesaleChangeServicePlansV2RespnseType)(results[0]));
        }

        /// <remarks/>
        public void WholesaleChangeServicePlansV2Async(WholesaleChangeServicePlansV2Type wholesaleChangeServicePlansV21)
        {
            this.WholesaleChangeServicePlansV2Async(wholesaleChangeServicePlansV21, null);
        }

        /// <remarks/>
        public void WholesaleChangeServicePlansV2Async(WholesaleChangeServicePlansV2Type wholesaleChangeServicePlansV21, object userState)
        {
            if ((this.WholesaleChangeServicePlansV2OperationCompleted == null))
            {
                this.WholesaleChangeServicePlansV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnWholesaleChangeServicePlansV2OperationCompleted);
            }
            this.InvokeAsync("WholesaleChangeServicePlansV2", new object[] {
                        wholesaleChangeServicePlansV21}, this.WholesaleChangeServicePlansV2OperationCompleted, userState);
        }

        private void OnWholesaleChangeServicePlansV2OperationCompleted(object arg)
        {
            if ((this.WholesaleChangeServicePlansV2Completed != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.WholesaleChangeServicePlansV2Completed(this, new WholesaleChangeServicePlansV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    [System.Xml.Serialization.XmlRootAttribute("wsMessageHeader", Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2", IsNullable = false)]
    public partial class WsMessageHeaderType : System.Web.Services.Protocols.SoapHeader
    {

        private TrackingMessageHeaderType trackingMessageHeaderField;

        private SecurityMessageHeaderType securityMessageHeaderField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public TrackingMessageHeaderType trackingMessageHeader
        {
            get
            {
                return this.trackingMessageHeaderField;
            }
            set
            {
                this.trackingMessageHeaderField = value;
            }
        }

        /// <remarks/>
        public SecurityMessageHeaderType securityMessageHeader
        {
            get
            {
                return this.securityMessageHeaderField;
            }
            set
            {
                this.securityMessageHeaderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    public partial class TrackingMessageHeaderType
    {

        private string applicationIdField;

        private string applicationUserIdField;

        private string consumerIdField;

        private string messageIdField;

        private string conversationIdField;

        private string timeToLiveField;

        private long replyCompletionCodeField;

        private bool replyCompletionCodeFieldSpecified;

        private System.DateTime messageDateTimeStampField;

        /// <remarks/>
        public string applicationId
        {
            get
            {
                return this.applicationIdField;
            }
            set
            {
                this.applicationIdField = value;
            }
        }

        /// <remarks/>
        public string applicationUserId
        {
            get
            {
                return this.applicationUserIdField;
            }
            set
            {
                this.applicationUserIdField = value;
            }
        }

        /// <remarks/>
        public string consumerId
        {
            get
            {
                return this.consumerIdField;
            }
            set
            {
                this.consumerIdField = value;
            }
        }

        /// <remarks/>
        public string messageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
            }
        }

        /// <remarks/>
        public string conversationId
        {
            get
            {
                return this.conversationIdField;
            }
            set
            {
                this.conversationIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "integer")]
        public string timeToLive
        {
            get
            {
                return this.timeToLiveField;
            }
            set
            {
                this.timeToLiveField = value;
            }
        }

        /// <remarks/>
        public long replyCompletionCode
        {
            get
            {
                return this.replyCompletionCodeField;
            }
            set
            {
                this.replyCompletionCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool replyCompletionCodeSpecified
        {
            get
            {
                return this.replyCompletionCodeFieldSpecified;
            }
            set
            {
                this.replyCompletionCodeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public System.DateTime messageDateTimeStamp
        {
            get
            {
                return this.messageDateTimeStampField;
            }
            set
            {
                this.messageDateTimeStampField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/wholesaleChangeServicePlans/v2/wholesale" +
        "ChangeServicePlansV2.xsd")]
    public partial class WholesaleChangeServicePlansV2RespnseType
    {

        private string confirmMsgField;

        /// <remarks/>
        public string confirmMsg
        {
            get
            {
                return this.confirmMsgField;
            }
            set
            {
                this.confirmMsgField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/wholesaleChangeServicePlans/v2/wholesale" +
        "ChangeServicePlansV2.xsd")]
    public partial class DataLinkInfoType
    {

        private string userNameField;

        private string passwordField;

        /// <remarks/>
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/wholesaleChangeServicePlans/v2/wholesale" +
        "ChangeServicePlansV2.xsd")]
    public partial class ProductDeploymentType
    {

        private string serviceCodeField;

        private System.DateTime serviceEffectiveDateField;

        private bool serviceEffectiveDateFieldSpecified;

        private System.DateTime serviceExpirationDateField;

        private bool serviceExpirationDateFieldSpecified;

        private string callForwardingNumberField;

        private DataLinkInfoType dataLinkInfoField;

        /// <remarks/>
        public string serviceCode
        {
            get
            {
                return this.serviceCodeField;
            }
            set
            {
                this.serviceCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime serviceEffectiveDate
        {
            get
            {
                return this.serviceEffectiveDateField;
            }
            set
            {
                this.serviceEffectiveDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serviceEffectiveDateSpecified
        {
            get
            {
                return this.serviceEffectiveDateFieldSpecified;
            }
            set
            {
                this.serviceEffectiveDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime serviceExpirationDate
        {
            get
            {
                return this.serviceExpirationDateField;
            }
            set
            {
                this.serviceExpirationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serviceExpirationDateSpecified
        {
            get
            {
                return this.serviceExpirationDateFieldSpecified;
            }
            set
            {
                this.serviceExpirationDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string callForwardingNumber
        {
            get
            {
                return this.callForwardingNumberField;
            }
            set
            {
                this.callForwardingNumberField = value;
            }
        }

        /// <remarks/>
        public DataLinkInfoType dataLinkInfo
        {
            get
            {
                return this.dataLinkInfoField;
            }
            set
            {
                this.dataLinkInfoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/wholesaleChangeServicePlans/v2/wholesale" +
        "ChangeServicePlansV2.xsd")]
    public partial class WholesaleChangeServicePlansV2Type
    {

        private string mdnField;

        private ProductDeploymentType pricePlanField;

        private ProductDeploymentType[] serviceListField;

        private ProductDeploymentType[] oldServiceListField;

        /// <remarks/>
        public string mdn
        {
            get
            {
                return this.mdnField;
            }
            set
            {
                this.mdnField = value;
            }
        }

        /// <remarks/>
        public ProductDeploymentType pricePlan
        {
            get
            {
                return this.pricePlanField;
            }
            set
            {
                this.pricePlanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("serviceRecord", IsNullable = false)]
        public ProductDeploymentType[] serviceList
        {
            get
            {
                return this.serviceListField;
            }
            set
            {
                this.serviceListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("serviceRecord", IsNullable = false)]
        public ProductDeploymentType[] oldServiceList
        {
            get
            {
                return this.oldServiceListField;
            }
            set
            {
                this.oldServiceListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
        "scriptionEnvelope.xsd")]
    public partial class SuspendSubscriptionRequest
    {

        private string mdnField;

        private string activityField;

        /// <remarks/>
        public string mdn
        {
            get
            {
                return this.mdnField;
            }
            set
            {
                this.mdnField = value;
            }
        }

        /// <remarks/>
        public string activity
        {
            get
            {
                return this.activityField;
            }
            set
            {
                this.activityField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
        "scriptionEnvelope.xsd")]
    public partial class RestoreSubscriptionRequest
    {

        private string mdnField;

        /// <remarks/>
        public string mdn
        {
            get
            {
                return this.mdnField;
            }
            set
            {
                this.mdnField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
        "scriptionEnvelope.xsd")]
    public partial class ExpireSubscriptionRequest
    {

        private string mdnField;

        private System.DateTime expireDateField;

        private bool expireDateFieldSpecified;

        /// <remarks/>
        public string mdn
        {
            get
            {
                return this.mdnField;
            }
            set
            {
                this.mdnField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime expireDate
        {
            get
            {
                return this.expireDateField;
            }
            set
            {
                this.expireDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool expireDateSpecified
        {
            get
            {
                return this.expireDateFieldSpecified;
            }
            set
            {
                this.expireDateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
        "scriptionEnvelope.xsd")]
    public partial class ConfirmMsg
    {

        private string confirmMsgField;

        /// <remarks/>
        public string confirmMsg
        {
            get
            {
                return this.confirmMsgField;
            }
            set
            {
                this.confirmMsgField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
        "scriptionEnvelope.xsd")]
    public partial class ProductDeployment
    {

        private string serviceCodeField;

        private System.DateTime serviceEffectiveDateField;

        private bool serviceEffectiveDateFieldSpecified;

        private System.DateTime serviceExpirationDateField;

        private bool serviceExpirationDateFieldSpecified;

        private string callForwardingNumberField;

        /// <remarks/>
        public string serviceCode
        {
            get
            {
                return this.serviceCodeField;
            }
            set
            {
                this.serviceCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime serviceEffectiveDate
        {
            get
            {
                return this.serviceEffectiveDateField;
            }
            set
            {
                this.serviceEffectiveDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serviceEffectiveDateSpecified
        {
            get
            {
                return this.serviceEffectiveDateFieldSpecified;
            }
            set
            {
                this.serviceEffectiveDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime serviceExpirationDate
        {
            get
            {
                return this.serviceExpirationDateField;
            }
            set
            {
                this.serviceExpirationDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool serviceExpirationDateSpecified
        {
            get
            {
                return this.serviceExpirationDateFieldSpecified;
            }
            set
            {
                this.serviceExpirationDateFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string callForwardingNumber
        {
            get
            {
                return this.callForwardingNumberField;
            }
            set
            {
                this.callForwardingNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/interfaces/WholesaleSubscriptionModify/v1/ModifySub" +
        "scriptionEnvelope.xsd")]
    public partial class ChangeServicePlansRequest
    {

        private string mdnField;

        private ProductDeployment pricePlanField;

        private ProductDeployment[] serviceListField;

        private ProductDeployment[] oldServiceListField;

        /// <remarks/>
        public string mdn
        {
            get
            {
                return this.mdnField;
            }
            set
            {
                this.mdnField = value;
            }
        }

        /// <remarks/>
        public ProductDeployment pricePlan
        {
            get
            {
                return this.pricePlanField;
            }
            set
            {
                this.pricePlanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("serviceRecord", IsNullable = false)]
        public ProductDeployment[] serviceList
        {
            get
            {
                return this.serviceListField;
            }
            set
            {
                this.serviceListField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("serviceRecord", IsNullable = false)]
        public ProductDeployment[] oldServiceList
        {
            get
            {
                return this.oldServiceListField;
            }
            set
            {
                this.oldServiceListField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    public partial class BasicCredentialInfoType
    {

        private string idField;

        private string passwordField;

        /// <remarks/>
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    public partial class SdcLoginCredentialsType
    {

        private string userIdField;

        private string passwordField;

        /// <remarks/>
        public string userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.4927")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://integration.sprint.com/common/header/WSMessageHeader/v2")]
    public partial class SecurityMessageHeaderType
    {

        private object itemField;

        private string corpIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("basicCredentialInfo", typeof(BasicCredentialInfoType))]
        [System.Xml.Serialization.XmlElementAttribute("pin", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("sdcLoginCredentials", typeof(SdcLoginCredentialsType))]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }

        /// <remarks/>
        public string corpId
        {
            get
            {
                return this.corpIdField;
            }
            set
            {
                this.corpIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ChangeServicePlansCompletedEventHandler(object sender, ChangeServicePlansCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ChangeServicePlansCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ChangeServicePlansCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ConfirmMsg Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ConfirmMsg)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void ExpireSubscriptionCompletedEventHandler(object sender, ExpireSubscriptionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ExpireSubscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal ExpireSubscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ConfirmMsg Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ConfirmMsg)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void RestoreSubscriptionCompletedEventHandler(object sender, RestoreSubscriptionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RestoreSubscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal RestoreSubscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ConfirmMsg Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ConfirmMsg)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void SuspendSubscriptionCompletedEventHandler(object sender, SuspendSubscriptionCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SuspendSubscriptionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal SuspendSubscriptionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ConfirmMsg Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ConfirmMsg)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    public delegate void WholesaleChangeServicePlansV2CompletedEventHandler(object sender, WholesaleChangeServicePlansV2CompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.4927")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WholesaleChangeServicePlansV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal WholesaleChangeServicePlansV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public WholesaleChangeServicePlansV2RespnseType Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((WholesaleChangeServicePlansV2RespnseType)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591