//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SprintWseLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservicesgateway.sprint.com:444/services/mvno/QueryCsaService/v1")]
        public string PingTestClient_com_sprint_webservicesgatewaytest_QueryCsaService {
            get {
                return ((string)(this["PingTestClient_com_sprint_webservicesgatewaytest_QueryCsaService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CN=321com, OU=TPA, OU=BMP, OU=Projects, O=Sprint, C=us")]
        public string userCertificateName {
            get {
                return ((string)(this["userCertificateName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservicesgateway.sprint.com:444/services/mvno/WholesaleSubscriptionDeta" +
            "ilService/v1")]
        public string PingTestClient_com_sprint_webservicesgatewaytest1_WholesaleSubscriptionDetailService {
            get {
                return ((string)(this["PingTestClient_com_sprint_webservicesgatewaytest1_WholesaleSubscriptionDetailServ" +
                    "ice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservicesgateway.sprint.com:444/services/mvno/WholesaleSubscriptionModi" +
            "fyService/v1")]
        public string PingTestClient_com_sprint_WholesaleSubscriptionModifyService_WholesaleSubscriptionModifyService {
            get {
                return ((string)(this["PingTestClient_com_sprint_WholesaleSubscriptionModifyService_WholesaleSubscriptio" +
                    "nModifyService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservicesgateway.sprint.com:444/services/mvno/WholesaleSubscriptionServ" +
            "ice/v1")]
        public string PingTestClient_com_sprint_WholesaleSubscriptionService_WholesaleSubscriptionService {
            get {
                return ((string)(this["PingTestClient_com_sprint_WholesaleSubscriptionService_WholesaleSubscriptionServi" +
                    "ce"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservicesgateway.sprint.com:444/services/mvno/WholesaleSwapSplitService" +
            "/v1")]
        public string PingTestClient_com_sprint_WholesaleSwapSplit_WholesaleSwapSplit {
            get {
                return ((string)(this["PingTestClient_com_sprint_WholesaleSwapSplit_WholesaleSwapSplit"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservicesgateway.sprint.com:444/services/mvno/WholesaleUsageInquiryServ" +
            "ice/v1")]
        public string PingTestClient_com_sprint_WholesaleUsageInquiryService_WholesaleUsageInquiryService {
            get {
                return ((string)(this["PingTestClient_com_sprint_WholesaleUsageInquiryService_WholesaleUsageInquiryServi" +
                    "ce"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservicesgateway.sprint.com:444/services/mvno/WholesaleWnpService/v1")]
        public string PingTestClient_com_sprint_WholesaleWnpService_WholesaleWnpService {
            get {
                return ((string)(this["PingTestClient_com_sprint_WholesaleWnpService_WholesaleWnpService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservicesgateway.sprint.com:444/services/mvno/WholesalePortMessageServi" +
            "ce/v1")]
        public string PingTestClient_com_sprint_WholesalePortMessageService_WholesalePortMessageService {
            get {
                return ((string)(this["PingTestClient_com_sprint_WholesalePortMessageService_WholesalePortMessageService" +
                    ""]));
            }
        }
    }
}
